import { createClient } from '@sanity/client'

const client = createClient({
  projectId: '6ogv1wx8',
  dataset: 'production',
  apiVersion: '2024-01-01',
  token: process.env.SANITY_WRITE_TOKEN,
  useCdn: false,
})

const locations = [
  // EUROPE - United Kingdom
  { city: 'London', country: 'United Kingdom', countryEmoji: '🇬🇧', continent: 'Europe', continentEmoji: '🌍', airport: 'London Heathrow Airport', emoji: '🏙️', heroDescription: 'London is one of the world\'s greatest cities and the experiences on offer are simply extraordinary. From West End theatre and world class museums to royal palaces and vibrant street markets, there is always something new to discover. Grab a hire car and the home counties, the Cotswolds and the stunning South Coast are all within easy reach.' },
  { city: 'Edinburgh', country: 'United Kingdom', countryEmoji: '🇬🇧', continent: 'Europe', continentEmoji: '🌍', airport: 'Edinburgh Airport', emoji: '🏰', heroDescription: 'Edinburgh is one of Europe\'s most dramatic and atmospheric cities. The castle, the Royal Mile and Arthur\'s Seat are just the beginning. Hire a car and the Scottish Highlands, Loch Ness, whisky distilleries and ancient castles are all within a comfortable drive.' },
  { city: 'Manchester', country: 'United Kingdom', countryEmoji: '🇬🇧', continent: 'Europe', continentEmoji: '🌍', airport: 'Manchester Airport', emoji: '🎵', heroDescription: 'Manchester is a city bursting with culture, music and sport. From the Northern Quarter\'s indie scene to the incredible museums and galleries, there is so much to experience. Hire a car and the Peak District, Lake District and Yorkshire Dales are all on your doorstep.' },
  { city: 'Glasgow', country: 'United Kingdom', countryEmoji: '🇬🇧', continent: 'Europe', continentEmoji: '🌍', airport: 'Glasgow Airport', emoji: '🎶', heroDescription: 'Glasgow is Scotland\'s most vibrant city with a world class arts scene, incredible food and some of the friendliest people you will ever meet. Hire a car and Loch Lomond, the Trossachs and the stunning Argyll coast are all just a short drive away.' },
  { city: 'Belfast', country: 'United Kingdom', countryEmoji: '🇬🇧', continent: 'Europe', continentEmoji: '🌍', airport: 'Belfast International Airport', emoji: '🏔️', heroDescription: 'Belfast has reinvented itself as one of Europe\'s most exciting city break destinations. The Titanic Quarter, the Cathedral Quarter and the incredible murals of the Falls and Shankill Roads tell a fascinating story. Hire a car and the Giant\'s Causeway and Causeway Coastal Route are unmissable.' },
  { city: 'Cardiff', country: 'United Kingdom', countryEmoji: '🇬🇧', continent: 'Europe', continentEmoji: '🌍', airport: 'Cardiff Airport', emoji: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', heroDescription: 'Cardiff is a compact and vibrant capital with a fantastic castle, brilliant rugby atmosphere and a buzzing food scene. Hire a car and the Brecon Beacons, the stunning Gower Peninsula and the waterfalls of the Vale of Neath are all within easy reach.' },
  { city: 'Inverness', country: 'United Kingdom', countryEmoji: '🇬🇧', continent: 'Europe', continentEmoji: '🌍', airport: 'Inverness Airport', emoji: '🦌', heroDescription: 'Inverness is the gateway to the Scottish Highlands and one of the most spectacular regions on earth. Hire a car and you have Loch Ness, Glencoe, the North Coast 500 and the Isle of Skye all within reach for unforgettable experiences.' },
  // EUROPE - Spain
  { city: 'Barcelona', country: 'Spain', countryEmoji: '🇪🇸', continent: 'Europe', continentEmoji: '🌍', airport: 'Barcelona El Prat Airport', emoji: '🏛️', heroDescription: 'Barcelona is one of Europe\'s most exciting cities with an extraordinary array of experiences. Gaudi\'s masterpieces, the Gothic Quarter, the Boqueria market and the vibrant beach scene are all incredible. Hire a car and the Costa Brava, the Pyrenees and the wine regions of Penedes and Priorat are all within easy reach.' },
  { city: 'Madrid', country: 'Spain', countryEmoji: '🇪🇸', continent: 'Europe', continentEmoji: '🌍', airport: 'Adolfo Suarez Madrid Barajas Airport', emoji: '👑', heroDescription: 'Madrid is Spain\'s passionate capital with world class art museums, incredible food markets and a nightlife scene that goes on until dawn. Hire a car and the medieval city of Toledo, the fairy tale palace of Segovia and the stunning Sierra de Guadarrama mountains are all just a short drive away.' },
  { city: 'Seville', country: 'Spain', countryEmoji: '🇪🇸', continent: 'Europe', continentEmoji: '🌍', airport: 'Seville Airport', emoji: '💃', heroDescription: 'Seville is the soul of Andalusia and one of Spain\'s most passionate cities. Flamenco, tapas, the stunning Alcazar palace and the magnificent cathedral are just the beginning. Hire a car and the white villages of the Sierra Nevada, the sherry bodegas of Jerez and the Donana National Park are all within reach.' },
  { city: 'Malaga', country: 'Spain', countryEmoji: '🇪🇸', continent: 'Europe', continentEmoji: '🌍', airport: 'Malaga Costa del Sol Airport', emoji: '🌞', heroDescription: 'Malaga is far more than just a gateway to the Costa del Sol. The birthplace of Picasso has a thriving arts scene, incredible tapas bars and a beautiful historic centre. Hire a car and the dramatic El Chorro gorge, the white villages of the Axarquia and the stunning Ronda are all unmissable experiences.' },
  { city: 'Valencia', country: 'Spain', countryEmoji: '🇪🇸', continent: 'Europe', continentEmoji: '🌍', airport: 'Valencia Airport', emoji: '🍊', heroDescription: 'Valencia is one of Spain\'s most underrated cities with incredible architecture, a world famous food scene and beautiful beaches. The City of Arts and Sciences is extraordinary. Hire a car and the Albufera natural park, the orange groves of the interior and the beautiful Castellon coast are all within easy reach.' },
  { city: 'Palma', country: 'Spain', countryEmoji: '🇪🇸', continent: 'Europe', continentEmoji: '🌍', airport: 'Palma de Mallorca Airport', emoji: '🌴', heroDescription: 'Palma is one of the Mediterranean\'s most beautiful cities and Mallorca has experiences to suit every taste. The dramatic Serra de Tramuntana mountains, the hidden coves of the north coast and the vibrant nightlife of the south are all extraordinary. A hire car is the best way to explore the island properly.' },
  { city: 'Tenerife', country: 'Spain', countryEmoji: '🇪🇸', continent: 'Europe', continentEmoji: '🌍', airport: 'Tenerife South Airport', emoji: '🌋', heroDescription: 'Tenerife is the Canary Islands\' most dramatic destination. Teide National Park is extraordinary and the contrast between the lush north and the arid south is remarkable. Hire a car and you can explore whale watching spots, ancient dragon trees, stunning volcanic beaches and charming colonial towns all in one trip.' },
  { city: 'Gran Canaria', country: 'Spain', countryEmoji: '🇪🇸', continent: 'Europe', continentEmoji: '🌍', airport: 'Gran Canaria Airport', emoji: '🏝️', heroDescription: 'Gran Canaria packs an extraordinary variety of landscapes and experiences into one island. The sand dunes of Maspalomas, the pine forests of the interior, the colourful carnival of Las Palmas and the ancient rock formations of Roque Nublo are all remarkable. Hire a car and discover them all.' },
  // EUROPE - France
  { city: 'Paris', country: 'France', countryEmoji: '🇫🇷', continent: 'Europe', continentEmoji: '🌍', airport: 'Charles de Gaulle Airport', emoji: '🗼', heroDescription: 'Paris is the city that invented the art of living well. The Louvre, the Eiffel Tower, the Seine and the extraordinary food and wine culture are all world class experiences. Hire a car and the Loire Valley chateaux, the Champagne vineyards and the D-Day beaches of Normandy are all within comfortable driving distance.' },
  { city: 'Nice', country: 'France', countryEmoji: '🇫🇷', continent: 'Europe', continentEmoji: '🌍', airport: 'Nice Cote d\'Azur Airport', emoji: '💐', heroDescription: 'Nice and the French Riviera offer some of the most glamorous experiences in Europe. The Promenade des Anglais, the old town and the extraordinary art scene are all wonderful. Hire a car and Monaco, Cannes, the perfume town of Grasse and the stunning Gorges du Verdon are all within easy reach.' },
  { city: 'Lyon', country: 'France', countryEmoji: '🇫🇷', continent: 'Europe', continentEmoji: '🌍', airport: 'Lyon Saint Exupery Airport', emoji: '🍷', heroDescription: 'Lyon is the gastronomic capital of France and a city of extraordinary depth and character. The Traboules, the Fourviere hill and the incredible bouchon restaurants are unforgettable experiences. Hire a car and the Beaujolais vineyards, the Rhone Valley and the stunning Ardeche gorge are all on your doorstep.' },
  { city: 'Bordeaux', country: 'France', countryEmoji: '🇫🇷', continent: 'Europe', continentEmoji: '🌍', airport: 'Bordeaux Merignac Airport', emoji: '🍷', heroDescription: 'Bordeaux is one of the world\'s great wine destinations and a beautifully restored city with fantastic experiences. The Cite du Vin wine museum, the stunning 18th century architecture and the incredible restaurant scene are all unmissable. Hire a car and the Saint Emilion vineyards, the Dune du Pilat and the beautiful Arcachon Bay are all nearby.' },
  { city: 'Marseille', country: 'France', countryEmoji: '🇫🇷', continent: 'Europe', continentEmoji: '🌍', airport: 'Marseille Provence Airport', emoji: '⛵', heroDescription: 'Marseille is France\'s most authentic and vibrant city with a raw energy that is completely unique. The Vieux Port, the MuCEM museum and the extraordinary Calanques national park right on the city\'s doorstep are incredible. Hire a car and the lavender fields of Provence, the Camargue and the Pont du Gard are all within easy reach.' },
  // EUROPE - Italy
  { city: 'Rome', country: 'Italy', countryEmoji: '🇮🇹', continent: 'Europe', continentEmoji: '🌍', airport: 'Rome Fiumicino Airport', emoji: '🏛️', heroDescription: 'Rome is the greatest open air museum in the world and the experiences on offer are simply overwhelming. The Colosseum, the Vatican, the Trevi Fountain and the extraordinary food culture are all unforgettable. Hire a car and the Tuscany hill towns, the Amalfi Coast and the ancient ruins of Pompeii are all within reach.' },
  { city: 'Florence', country: 'Italy', countryEmoji: '🇮🇹', continent: 'Europe', continentEmoji: '🌍', airport: 'Florence Peretola Airport', emoji: '🎨', heroDescription: 'Florence is the birthplace of the Renaissance and every street corner holds an extraordinary work of art or architecture. The Uffizi, the Duomo and the Ponte Vecchio are iconic experiences. Hire a car and the Chianti wine country, Siena, San Gimignano and the stunning Val d\'Orcia are all just a short drive away.' },
  { city: 'Venice', country: 'Italy', countryEmoji: '🇮🇹', continent: 'Europe', continentEmoji: '🌍', airport: 'Venice Marco Polo Airport', emoji: '🚤', heroDescription: 'Venice is unlike anywhere else on earth and the experience of wandering its canals and bridges is truly magical. The Doge\'s Palace, St Mark\'s Square and a gondola ride are unforgettable. Hire a car and the Prosecco hills, the beautiful city of Verona and the stunning Dolomites are all within easy reach.' },
  { city: 'Milan', country: 'Italy', countryEmoji: '🇮🇹', continent: 'Europe', continentEmoji: '🌍', airport: 'Milan Malpensa Airport', emoji: '👗', heroDescription: 'Milan is Italy\'s most cosmopolitan city and a world capital of fashion, design and food. The Duomo, Leonardo\'s Last Supper and the Brera district are all extraordinary experiences. Hire a car and the beautiful Lake Como, Lake Maggiore and the dramatic Dolomites are all within easy striking distance.' },
  { city: 'Naples', country: 'Italy', countryEmoji: '🇮🇹', continent: 'Europe', continentEmoji: '🌍', airport: 'Naples International Airport', emoji: '🍕', heroDescription: 'Naples is chaotic, passionate and utterly unforgettable. The pizza, the street life and the extraordinary National Archaeological Museum are all incredible experiences. Hire a car and Pompeii, the Amalfi Coast, the island of Capri and the stunning Cilento coast are all on your doorstep.' },
  { city: 'Palermo', country: 'Italy', countryEmoji: '🇮🇹', continent: 'Europe', continentEmoji: '🌍', airport: 'Palermo Airport', emoji: '🍋', heroDescription: 'Palermo is one of the Mediterranean\'s most fascinating cities with extraordinary Arab-Norman architecture, incredible street food markets and a vibrant local culture. Hire a car and the Valley of the Temples, the baroque towns of the south east, Mount Etna and the stunning beaches of Sicily are all within reach.' },
  // EUROPE - Portugal
  { city: 'Lisbon', country: 'Portugal', countryEmoji: '🇵🇹', continent: 'Europe', continentEmoji: '🌍', airport: 'Humberto Delgado Airport', emoji: '🎸', heroDescription: 'Lisbon is one of Europe\'s most soulful and atmospheric capitals. Fado music drifting from a restaurant, riding the famous yellow trams and watching the sunset from the Alfama are all magical experiences. Hire a car and the fairy tale palaces of Sintra, the great surf beaches of Cascais and the Douro Valley vineyards are all within easy reach.' },
  { city: 'Porto', country: 'Portugal', countryEmoji: '🇵🇹', continent: 'Europe', continentEmoji: '🌍', airport: 'Francisco Sa Carneiro Airport', emoji: '🍷', heroDescription: 'Porto is one of Europe\'s most romantic and characterful cities. The Ribeira waterfront, the azulejo-covered buildings, the port wine cellars of Vila Nova de Gaia and the extraordinary Livraria Lello bookshop are all unforgettable. Hire a car and the stunning Douro Valley wine terraces are one of Europe\'s greatest road trip experiences.' },
  { city: 'Faro', country: 'Portugal', countryEmoji: '🇵🇹', continent: 'Europe', continentEmoji: '🌍', airport: 'Faro Airport', emoji: '🏖️', heroDescription: 'Faro is the gateway to the Algarve and a charming walled town in its own right. The Ria Formosa natural park is extraordinary. Hire a car and the dramatic sea caves and rock arches of Lagos and Ponta da Piedade, the hidden beaches of the western Algarve and the traditional villages of the Serra de Monchique are all wonderful experiences.' },
  { city: 'Funchal', country: 'Portugal', countryEmoji: '🇵🇹', continent: 'Europe', continentEmoji: '🌍', airport: 'Madeira Airport', emoji: '🌺', heroDescription: 'Madeira is one of the world\'s most beautiful islands and Funchal is a brilliant base for exploring it. The traditional toboggan ride, the flower market and the incredible botanical garden are all memorable experiences. Hire a car and the dramatic levada walks, the volcanic landscapes of the interior and the stunning north coast are all extraordinary.' },
  // EUROPE - Greece
  { city: 'Athens', country: 'Greece', countryEmoji: '🇬🇷', continent: 'Europe', continentEmoji: '🌍', airport: 'Athens International Airport', emoji: '🏛️', heroDescription: 'Athens is one of the world\'s great historic cities and the experiences it offers are truly humbling. Standing on the Acropolis, exploring the ancient Agora and wandering the Plaka neighbourhood are all extraordinary. Hire a car and the stunning temples of the Peloponnese, the oracle at Delphi and the beautiful Attica coast are all within reach.' },
  { city: 'Heraklion', country: 'Greece', countryEmoji: '🇬🇷', continent: 'Europe', continentEmoji: '🌍', airport: 'Heraklion International Airport', emoji: '🏺', heroDescription: 'Crete is Greece\'s most diverse and rewarding island and Heraklion is the perfect base. The Minoan palace of Knossos, the stunning Samaria Gorge walk and the atmospheric old harbour are all unmissable. Hire a car and the beautiful south coast beaches, the White Mountains and the charming villages of the interior are all incredible experiences.' },
  { city: 'Rhodes', country: 'Greece', countryEmoji: '🇬🇷', continent: 'Europe', continentEmoji: '🌍', airport: 'Rhodes International Airport', emoji: '🌹', heroDescription: 'Rhodes is one of the most beautiful islands in the Mediterranean with a UNESCO listed medieval old town that is simply extraordinary. The Street of the Knights, the Valley of the Butterflies and the ancient acropolis of Lindos are all memorable experiences. A hire car lets you explore every corner of this stunning island.' },
  { city: 'Corfu', country: 'Greece', countryEmoji: '🇬🇷', continent: 'Europe', continentEmoji: '🌍', airport: 'Corfu International Airport', emoji: '🫒', heroDescription: 'Corfu is one of Greece\'s most lush and beautiful islands with a fascinating Venetian heritage. The old town, the Achilleion palace and the beautiful Paleokastritsa lagoon are all extraordinary experiences. Hire a car and you can discover the hidden beaches of the north coast, the olive groves of the interior and the dramatic west coast cliffs.' },
  // EUROPE - Germany
  { city: 'Munich', country: 'Germany', countryEmoji: '🇩🇪', continent: 'Europe', continentEmoji: '🌍', airport: 'Munich Airport', emoji: '🍺', heroDescription: 'Munich is one of Europe\'s most liveable and experience-rich cities. The English Garden, the Deutsches Museum, the incredible beer gardens and the world famous Oktoberfest are all extraordinary. Hire a car and the fairy tale castle of Neuschwanstein, the stunning Bavarian Alps and the beautiful lake district of the Chiemsee are all just an hour away.' },
  { city: 'Berlin', country: 'Germany', countryEmoji: '🇩🇪', continent: 'Europe', continentEmoji: '🌍', airport: 'Berlin Brandenburg Airport', emoji: '🐻', heroDescription: 'Berlin is one of the world\'s most dynamic and creatively exciting cities. The Brandenburg Gate, the Holocaust Memorial, Museum Island and the extraordinary street art scene are all powerful experiences. Hire a car and the beautiful Spreewald, the stunning Sanssouci palace in Potsdam and the Baltic Sea coast are all within easy reach.' },
  { city: 'Hamburg', country: 'Germany', countryEmoji: '🇩🇪', continent: 'Europe', continentEmoji: '🌍', airport: 'Hamburg Airport', emoji: '⚓', heroDescription: 'Hamburg is Germany\'s most international city with extraordinary experiences in its warehouse district, its vibrant Reeperbahn and its incredible harbour. The Elbphilharmonie concert hall is world class. Hire a car and the stunning Luneburg Heath, the beautiful Schleswig Holstein coast and the charming medieval city of Lubeck are all nearby.' },
  { city: 'Frankfurt', country: 'Germany', countryEmoji: '🇩🇪', continent: 'Europe', continentEmoji: '🌍', airport: 'Frankfurt Airport', emoji: '🏦', heroDescription: 'Frankfurt is much more than just a financial centre. The Romerberg old town, the superb museum embankment and the incredible apple wine taverns of Sachsenhausen are all great experiences. Hire a car and the romantic Rhine Valley, the medieval town of Heidelberg and the beautiful Black Forest are all within easy striking distance.' },
  // EUROPE - Netherlands
  { city: 'Amsterdam', country: 'Netherlands', countryEmoji: '🇳🇱', continent: 'Europe', continentEmoji: '🌍', airport: 'Amsterdam Schiphol Airport', emoji: '🌷', heroDescription: 'Amsterdam is one of Europe\'s most charming and experience-rich cities. The canal houses, the Anne Frank House, the Rijksmuseum and the incredible cycling culture are all wonderful. Hire a car and the tulip fields of the Bollenstreek, the windmills of Kinderdijk and the beautiful university city of Leiden are all just a short drive away.' },
  // EUROPE - Belgium
  { city: 'Brussels', country: 'Belgium', countryEmoji: '🇧🇪', continent: 'Europe', continentEmoji: '🌍', airport: 'Brussels Airport', emoji: '🍫', heroDescription: 'Brussels is the unexpected gem of Europe. The Grand Place, the Art Nouveau architecture, the extraordinary chocolate and waffle culture and the world class comic strip museum are all wonderful experiences. Hire a car and the medieval canals of Bruges, the vibrant city of Ghent and the beautiful Ardennes forest are all within easy reach.' },
  // EUROPE - Switzerland
  { city: 'Geneva', country: 'Switzerland', countryEmoji: '🇨🇭', continent: 'Europe', continentEmoji: '🌍', airport: 'Geneva Airport', emoji: '⌚', heroDescription: 'Geneva sits at the edge of a beautiful lake surrounded by the Alps and Jura mountains and offers extraordinary experiences. The Jet d\'Eau, the Old Town and CERN are all fascinating. Hire a car and the French ski resorts of Chamonix and Megeve, the beautiful Lavaux wine terraces and the stunning Grindelwald are all within reach.' },
  { city: 'Zurich', country: 'Switzerland', countryEmoji: '🇨🇭', continent: 'Europe', continentEmoji: '🌍', airport: 'Zurich Airport', emoji: '🏔️', heroDescription: 'Zurich is consistently rated one of the world\'s most liveable cities and the experiences it offers are exceptional. The Old Town, the lake promenade and the extraordinary art and design scene are all wonderful. Hire a car and the Rhine Falls, the beautiful Lake Constance and the dramatic Jungfrau region are all within easy reach.' },
  // EUROPE - Austria
  { city: 'Vienna', country: 'Austria', countryEmoji: '🇦🇹', continent: 'Europe', continentEmoji: '🌍', airport: 'Vienna International Airport', emoji: '🎭', heroDescription: 'Vienna is one of Europe\'s most imperial and cultured cities. The Schonbrunn Palace, the Spanish Riding School, the Vienna Opera House and the extraordinary coffee house culture are all unforgettable experiences. Hire a car and the stunning Wachau Valley vineyards, the beautiful Salzkammergut lakes and the dramatic Alps are all within easy reach.' },
  { city: 'Salzburg', country: 'Austria', countryEmoji: '🇦🇹', continent: 'Europe', continentEmoji: '🌍', airport: 'Salzburg Airport', emoji: '🎵', heroDescription: 'Salzburg is one of Europe\'s most beautiful cities and the birthplace of Mozart. The fortress, the Mirabell Gardens, the Sound of Music tour and the extraordinary music festival are all wonderful experiences. Hire a car and the stunning Salzkammergut lake district, the Berchtesgaden Eagle\'s Nest and the dramatic Grossglockner Alpine road are all nearby.' },
  // EUROPE - Czech Republic
  { city: 'Prague', country: 'Czech Republic', countryEmoji: '🇨🇿', continent: 'Europe', continentEmoji: '🌍', airport: 'Vaclav Havel Airport Prague', emoji: '🏰', heroDescription: 'Prague is one of Europe\'s most beautiful and best preserved cities with extraordinary experiences at every turn. The Old Town Square, the Charles Bridge, the castle and the incredible craft beer scene are all unforgettable. Hire a car and the beautiful spa town of Karlovy Vary, the stunning Bohemian Switzerland National Park and the fairy tale town of Cesky Krumlov are all within reach.' },
  // EUROPE - Hungary
  { city: 'Budapest', country: 'Hungary', countryEmoji: '🇭🇺', continent: 'Europe', continentEmoji: '🌍', airport: 'Budapest Ferenc Liszt International Airport', emoji: '🌉', heroDescription: 'Budapest is one of Europe\'s most dramatic and romantic cities. Soaking in a thermal bath, watching the sunset from the Fisherman\'s Bastion and exploring the ruin bars of the Jewish Quarter are all extraordinary experiences. Hire a car and the beautiful Danube Bend, the wine region of Eger and the stunning Bukk National Park are all nearby.' },
  // EUROPE - Croatia
  { city: 'Dubrovnik', country: 'Croatia', countryEmoji: '🇭🇷', continent: 'Europe', continentEmoji: '🌍', airport: 'Dubrovnik Airport', emoji: '🏰', heroDescription: 'Dubrovnik is one of the most beautiful cities in the world and walking its ancient city walls is an unforgettable experience. The Stradun, the Fort Lovrijenac and kayaking around the city walls are all wonderful. Hire a car and the stunning Peljesac wine peninsula, the Neretva delta and the beautiful Mljet National Park are all within easy reach.' },
  { city: 'Split', country: 'Croatia', countryEmoji: '🇭🇷', continent: 'Europe', continentEmoji: '🌍', airport: 'Split Airport', emoji: '🌊', heroDescription: 'Split is one of the Mediterranean\'s most vibrant cities built around the extraordinary Diocletian\'s Palace. Exploring the palace, watching the klapa singers in the peristyle and swimming off the Bacvice beach are all memorable experiences. Hire a car and the Krka waterfalls, the Cetina Canyon rafting and the stunning Plitvice Lakes are all within reach.' },
  // EUROPE - Turkey (Istanbul only as European side)
  { city: 'Istanbul', country: 'Turkey', countryEmoji: '🇹🇷', continent: 'Europe', continentEmoji: '🌍', airport: 'Istanbul Airport', emoji: '🕌', heroDescription: 'Istanbul is one of the world\'s most extraordinary cities straddling two continents. The Hagia Sophia, the Blue Mosque, the Grand Bazaar and a Bosphorus cruise are all unforgettable experiences. Hire a car and the beautiful Bosphorus villages, the Princes Islands and the stunning Thracian countryside are all within easy reach.' },
  // EUROPE - Poland
  { city: 'Krakow', country: 'Poland', countryEmoji: '🇵🇱', continent: 'Europe', continentEmoji: '🌍', airport: 'Krakow John Paul II International Airport', emoji: '👑', heroDescription: 'Krakow is one of Europe\'s most beautiful and historically significant cities. The Main Market Square, the Wawel Castle, the Jewish Quarter of Kazimierz and the profound Auschwitz memorial are all important experiences. Hire a car and the stunning Tatra Mountains, the wooden churches of the Malopolska region and the stunning Ojcow National Park are all nearby.' },
  // ASIA - Japan
  { city: 'Tokyo', country: 'Japan', countryEmoji: '🇯🇵', continent: 'Asia', continentEmoji: '🌏', airport: 'Tokyo Narita International Airport', emoji: '🗼', heroDescription: 'Tokyo is one of the world\'s most extraordinary cities and the experiences it offers are like nowhere else on earth. From the neon lights of Shinjuku and the tranquil temples of Asakusa to the teamLab digital art installations and the extraordinary food scene, every moment is unforgettable. Hire a car and Mount Fuji, the temples of Nikko and the beautiful Izu Peninsula are all within reach.' },
  { city: 'Osaka', country: 'Japan', countryEmoji: '🇯🇵', continent: 'Asia', continentEmoji: '🌏', airport: 'Osaka Kansai International Airport', emoji: '🏯', heroDescription: 'Osaka is Japan\'s most fun and food obsessed city. Dotonbori, the street food of Shinsekai, the extraordinary Osaka Castle and the Universal Studios Japan theme park are all brilliant experiences. Hire a car and the ancient temples and geisha districts of Kyoto, the deer park of Nara and the beautiful Kii Peninsula are all within easy reach.' },
  { city: 'Kyoto', country: 'Japan', countryEmoji: '🇯🇵', continent: 'Asia', continentEmoji: '🌏', airport: 'Osaka Kansai International Airport', emoji: '⛩️', heroDescription: 'Kyoto is Japan\'s cultural heart and the experiences it offers are simply extraordinary. The Fushimi Inari shrine with its thousands of torii gates, the bamboo grove of Arashiyama, the geisha district of Gion and the stunning Kinkakuji golden pavilion are all unforgettable. Hire a car and the rural Tamba region and the beautiful Wakasa Bay coast are nearby.' },
  { city: 'Sapporo', country: 'Japan', countryEmoji: '🇯🇵', continent: 'Asia', continentEmoji: '🌏', airport: 'New Chitose Airport', emoji: '❄️', heroDescription: 'Sapporo is the gateway to Hokkaido and offers experiences unlike anywhere else in Japan. The extraordinary Snow Festival, the world class ski resorts of Niseko and Furano, the stunning caldera lakes and the incredible seafood are all unforgettable. Hire a car and the Shikotsu Toya National Park, the Furano lavender fields and the dramatic Shiretoko Peninsula are all within reach.' },
  // ASIA - Thailand
  { city: 'Bangkok', country: 'Thailand', countryEmoji: '🇹🇭', continent: 'Asia', continentEmoji: '🌏', airport: 'Suvarnabhumi Airport', emoji: '🛕', heroDescription: 'Bangkok is one of Asia\'s most exciting and sensory cities. The Grand Palace, Wat Pho, the floating markets, the rooftop bars and the extraordinary street food scene are all incredible experiences. Hire a car and the ancient capital of Ayutthaya, the stunning Khao Yai National Park and the River Kwai are all within easy reach for day trips.' },
  { city: 'Chiang Mai', country: 'Thailand', countryEmoji: '🇹🇭', continent: 'Asia', continentEmoji: '🌏', airport: 'Chiang Mai International Airport', emoji: '🌿', heroDescription: 'Chiang Mai is the cultural capital of northern Thailand and a city of extraordinary experiences. The Yi Peng lantern festival, the elephant sanctuaries, the cooking schools, the ancient temples and the night bazaar are all wonderful. Hire a car and the Doi Inthanon National Park, the hill tribe villages and the dramatic Mae Hong Son loop are all within reach.' },
  { city: 'Phuket', country: 'Thailand', countryEmoji: '🇹🇭', continent: 'Asia', continentEmoji: '🌏', airport: 'Phuket International Airport', emoji: '🏖️', heroDescription: 'Phuket is Thailand\'s most famous island and offers extraordinary experiences both on and off the beaten track. The stunning Phang Nga Bay sea kayaking, the beautiful Big Buddha, the old town architecture and the island hopping are all memorable. Hire a car and the beautiful Khao Sok National Park and the quieter beaches of the north are all within reach.' },
  // ASIA - Indonesia
  { city: 'Bali', country: 'Indonesia', countryEmoji: '🇮🇩', continent: 'Asia', continentEmoji: '🌏', airport: 'Ngurah Rai International Airport', emoji: '🌺', heroDescription: 'Bali is one of the world\'s most magical destinations with experiences that touch the soul. The sacred monkey forest, the rice terraces of Tegalalang, the water temples, the traditional Kecak fire dance and the surf culture of Seminyak are all extraordinary. Hire a car and you can explore the volcanic landscapes of Mount Batur, the artistic town of Ubud and the stunning Uluwatu clifftop temple.' },
  // ASIA - Singapore
  { city: 'Singapore', country: 'Singapore', countryEmoji: '🇸🇬', continent: 'Asia', continentEmoji: '🌏', airport: 'Singapore Changi Airport', emoji: '🌿', heroDescription: 'Singapore is one of the world\'s most extraordinary cities and a place where experiences come thick and fast. Gardens by the Bay, the Marina Bay Sands skypark, the hawker centres, the colonial heritage of the civic district and the extraordinary diversity of cultures are all remarkable. Hire a car and use this incredible city as your base for exploring the wider region.' },
  // ASIA - India
  { city: 'Delhi', country: 'India', countryEmoji: '🇮🇳', continent: 'Asia', continentEmoji: '🌏', airport: 'Indira Gandhi International Airport', emoji: '🕌', heroDescription: 'Delhi is one of the world\'s great historic cities and a place of extraordinary contrasts and experiences. The Red Fort, the Qutb Minar, the Humayun\'s Tomb and the chaotic beauty of Old Delhi are all unforgettable. Hire a car and the Taj Mahal at Agra, the pink city of Jaipur and the sacred ghats of Varanasi are all within reach on the Golden Triangle route.' },
  { city: 'Mumbai', country: 'India', countryEmoji: '🇮🇳', continent: 'Asia', continentEmoji: '🌏', airport: 'Chhatrapati Shivaji Maharaj International Airport', emoji: '🎬', heroDescription: 'Mumbai is India\'s most cosmopolitan and dynamic city. The Gateway of India, the Elephanta Caves, the Dharavi slum tour, the Bollywood film city and the extraordinary street food of Juhu Beach are all incredible experiences. Hire a car and the hill stations of Lonavala, the caves of Ajanta and Ellora and the stunning Konkan coast are all within reach.' },
  { city: 'Goa', country: 'India', countryEmoji: '🇮🇳', continent: 'Asia', continentEmoji: '🌏', airport: 'Goa International Airport', emoji: '🏖️', heroDescription: 'Goa is India\'s most laid back and experience-rich beach destination. The Portuguese colonial heritage, the spice plantation tours, the incredible seafood, the yoga retreats and the stunning beaches of the north and south are all wonderful. Hire a car and the hidden waterfalls of Dudhsagar, the wildlife sanctuary of Bhagwan Mahaveer and the charming old quarter of Panjim are all within easy reach.' },
  // MIDDLE EAST - UAE
  { city: 'Dubai', country: 'UAE', countryEmoji: '🇦🇪', continent: 'Middle East', continentEmoji: '🌍', airport: 'Dubai International Airport', emoji: '🏙️', heroDescription: 'Dubai is a city of extraordinary ambition and the experiences it offers are unlike anywhere else. The Burj Khalifa, the Palm Jumeirah, the gold souk, a desert safari and the incredible dining scene are all unforgettable. Hire a car and Abu Dhabi\'s Sheikh Zayed Grand Mosque, the Hajar Mountains and the beautiful Musandam peninsula are all within easy reach.' },
  { city: 'Abu Dhabi', country: 'UAE', countryEmoji: '🇦🇪', continent: 'Middle East', continentEmoji: '🌍', airport: 'Abu Dhabi International Airport', emoji: '🕌', heroDescription: 'Abu Dhabi is one of the Middle East\'s most culturally rich destinations. The Sheikh Zayed Grand Mosque is one of the most beautiful buildings in the world. The Louvre Abu Dhabi, the Yas Island theme parks, the Liwa Oasis desert and the Formula 1 circuit are all extraordinary experiences. Hire a car and explore the wider UAE at your own pace.' },
  // MIDDLE EAST - Turkey (Asian side)
  { city: 'Antalya', country: 'Turkey', countryEmoji: '🇹🇷', continent: 'Middle East', continentEmoji: '🌍', airport: 'Antalya Airport', emoji: '🏖️', heroDescription: 'Antalya is the gateway to Turkey\'s stunning Turquoise Coast and the experiences here are extraordinary. The ancient Roman harbour, the Duden waterfalls, the incredible Lycian ruins of Termessos and the old quarter of Kaleici are all wonderful. Hire a car and the ancient cities of Perge and Aspendos, the dramatic Koprulu Canyon and the beautiful Saklikent gorge are all within easy reach.' },
  { city: 'Cappadocia', country: 'Turkey', countryEmoji: '🇹🇷', continent: 'Middle East', continentEmoji: '🌍', airport: 'Nevsehir Kapadokya Airport', emoji: '🎈', heroDescription: 'Cappadocia is one of the world\'s most extraordinary landscapes and the experiences here are truly unique. A hot air balloon flight over the fairy chimneys at sunrise, exploring the underground cities of Derinkuyu, staying in a cave hotel and hiking the Rose Valley are all unforgettable. Hire a car and discover every hidden corner of this magical region.' },
  // NORTH AMERICA - USA
  { city: 'New York', country: 'USA', countryEmoji: '🇺🇸', continent: 'North America', continentEmoji: '🌎', airport: 'John F Kennedy International Airport', emoji: '🗽', heroDescription: 'New York City is one of the world\'s greatest experience destinations. Central Park, the High Line, the Metropolitan Museum, a Broadway show, the Brooklyn food scene and the extraordinary energy of Times Square are all unforgettable. Hire a car and the Hudson Valley, the Hamptons, Niagara Falls and the stunning New England fall foliage are all within easy reach.' },
  { city: 'Los Angeles', country: 'USA', countryEmoji: '🇺🇸', continent: 'North America', continentEmoji: '🌎', airport: 'Los Angeles International Airport', emoji: '🌴', heroDescription: 'Los Angeles is the entertainment capital of the world and the experiences it offers are extraordinary. The Getty Center, the Hollywood Walk of Fame, Venice Beach, a Warner Brothers studio tour and the incredible food scene of Silver Lake are all wonderful. Hire a car and the Pacific Coast Highway, Yosemite, Joshua Tree and the Grand Canyon are all epic road trips from LA.' },
  { city: 'Miami', country: 'USA', countryEmoji: '🇺🇸', continent: 'North America', continentEmoji: '🌎', airport: 'Miami International Airport', emoji: '🌊', heroDescription: 'Miami is one of America\'s most vibrant and culturally rich cities. The Art Deco architecture of South Beach, the Wynwood Walls street art district, the Little Havana food scene and the incredible nightlife are all extraordinary experiences. Hire a car and the Florida Keys, the Everglades airboat tours, the Kennedy Space Center and the beautiful Gulf Coast beaches are all within easy reach.' },
  { city: 'Las Vegas', country: 'USA', countryEmoji: '🇺🇸', continent: 'North America', continentEmoji: '🌎', airport: 'Harry Reid International Airport', emoji: '🎰', heroDescription: 'Las Vegas is the most extraordinary city on earth for experiences. The shows, the casinos, the incredible restaurants of celebrity chefs and the sheer spectacle of the Strip are all unforgettable. Hire a car and the Grand Canyon South Rim, the otherworldly Valley of Fire, the stunning Zion National Park and the beautiful Lake Mead are all within easy driving distance.' },
  { city: 'Orlando', country: 'USA', countryEmoji: '🇺🇸', continent: 'North America', continentEmoji: '🌎', airport: 'Orlando International Airport', emoji: '🎢', heroDescription: 'Orlando is the world capital of theme park experiences. Walt Disney World, Universal Studios, SeaWorld and LEGOLAND are all extraordinary. Hire a car and the beautiful Kennedy Space Center, the natural spring swimming holes of the Florida state parks, the gorgeous Gulf Coast beaches of Clearwater and the charming historic district of St Augustine are all within easy reach.' },
  { city: 'San Francisco', country: 'USA', countryEmoji: '🇺🇸', continent: 'North America', continentEmoji: '🌎', airport: 'San Francisco International Airport', emoji: '🌉', heroDescription: 'San Francisco is one of America\'s most beautiful and culturally rich cities. The Golden Gate Bridge, Alcatraz, the cable cars, the Ferry Building food market and the extraordinary street art of the Mission District are all wonderful experiences. Hire a car and the Napa Valley wine country, the breathtaking Big Sur coastline and the stunning Yosemite Valley are all iconic road trips.' },
  { city: 'Chicago', country: 'USA', countryEmoji: '🇺🇸', continent: 'North America', continentEmoji: '🌎', airport: "O'Hare International Airport", emoji: '🌬️', heroDescription: 'Chicago is one of America\'s greatest cities with an extraordinary array of experiences. The Cloud Gate sculpture, the Art Institute, the deep dish pizza, the blues clubs of the South Side and the incredible architecture boat tours are all unmissable. Hire a car and the stunning Indiana Dunes, the beautiful Door County peninsula and the Great Lakes are all within easy reach.' },
  { city: 'Honolulu', country: 'USA', countryEmoji: '🇺🇸', continent: 'North America', continentEmoji: '🌎', airport: 'Daniel K Inouye International Airport', emoji: '🌺', heroDescription: 'Honolulu and the island of Oahu offer extraordinary Hawaiian experiences. Pearl Harbor, Diamond Head, the North Shore surfing scene, a traditional luau and the incredible snorkelling of Hanauma Bay are all unforgettable. Hire a car and you can explore every corner of this beautiful island from the lush windward coast to the dramatic Pali Lookout.' },
  { city: 'Denver', country: 'USA', countryEmoji: '🇺🇸', continent: 'North America', continentEmoji: '🌎', airport: 'Denver International Airport', emoji: '🏔️', heroDescription: 'Denver is the gateway to the Rocky Mountains and one of America\'s most outdoor-focused cities. The Red Rocks Amphitheatre, the craft brewery scene, the Denver Art Museum and the incredible mountain views are all wonderful. Hire a car and Rocky Mountain National Park, the stunning Mesa Verde cliff dwellings, the Great Sand Dunes and the world class ski resorts are all within reach.' },
  { city: 'Seattle', country: 'USA', countryEmoji: '🇺🇸', continent: 'North America', continentEmoji: '🌎', airport: 'Seattle Tacoma International Airport', emoji: '☕', heroDescription: 'Seattle is one of America\'s most beautiful and innovative cities. The Pike Place Market fish toss, the Space Needle, the extraordinary Museum of Pop Culture, the coffee culture and the incredible seafood scene are all wonderful experiences. Hire a car and Mount Rainier, the stunning Olympic Peninsula rain forest, the beautiful San Juan Islands and the dramatic North Cascades are all within easy reach.' },
  { city: 'New Orleans', country: 'USA', countryEmoji: '🇺🇸', continent: 'North America', continentEmoji: '🌎', airport: 'Louis Armstrong New Orleans International Airport', emoji: '🎺', heroDescription: 'New Orleans is one of America\'s most unique and experience-rich cities. The jazz clubs of Frenchmen Street, the extraordinary Mardi Gras celebrations, the incredible Creole food scene, the voodoo history and the beautiful Garden District architecture are all unforgettable. Hire a car and the Mississippi plantation houses, the Cajun bayou country and the Gulf Coast beaches are all within easy reach.' },
  // NORTH AMERICA - Canada
  { city: 'Toronto', country: 'Canada', countryEmoji: '🇨🇦', continent: 'North America', continentEmoji: '🌎', airport: 'Toronto Pearson International Airport', emoji: '🍁', heroDescription: 'Toronto is one of the world\'s most multicultural cities and the experiences it offers reflect that extraordinary diversity. The CN Tower, the distillery district, the incredible food scene of Kensington Market and the vibrant arts culture are all wonderful. Hire a car and the breathtaking Niagara Falls, the beautiful wine country of Niagara on the Lake and the stunning Georgian Bay are all within easy reach.' },
  { city: 'Vancouver', country: 'Canada', countryEmoji: '🇨🇦', continent: 'North America', continentEmoji: '🌎', airport: 'Vancouver International Airport', emoji: '🏔️', heroDescription: 'Vancouver is consistently rated one of the world\'s most beautiful cities and the experiences it offers are extraordinary. Stanley Park, Granville Island food market, the Capilano suspension bridge and the incredible mountain backdrop are all wonderful. Hire a car and the Sea to Sky Highway to Whistler, the stunning Gulf Islands, the beautiful Okanagan wine country and the dramatic Pacific Rim National Park are all within reach.' },
  { city: 'Montreal', country: 'Canada', countryEmoji: '🇨🇦', continent: 'North America', continentEmoji: '🌎', airport: 'Montreal Pierre Elliott Trudeau International Airport', emoji: '🎭', heroDescription: 'Montreal is Canada\'s most European and culturally vibrant city. The Jazz Festival, the incredible French food scene, the underground city, the beautiful Mount Royal park and the extraordinary street art are all wonderful experiences. Hire a car and the stunning Laurentian Mountains, the charming Eastern Townships wine country and the beautiful historic city of Quebec are all within easy reach.' },
  { city: 'Calgary', country: 'Canada', countryEmoji: '🇨🇦', continent: 'North America', continentEmoji: '🌎', airport: 'Calgary International Airport', emoji: '🤠', heroDescription: 'Calgary is the gateway to the Canadian Rockies and one of the world\'s great outdoor experience destinations. The famous Calgary Stampede rodeo is extraordinary. Hire a car and the stunning Banff National Park, the beautiful Lake Louise, the dramatic Columbia Icefield, the Icefields Parkway and the incredible Jasper National Park are all within reach for unforgettable experiences.' },
  // NORTH AMERICA - Mexico
  { city: 'Cancun', country: 'Mexico', countryEmoji: '🇲🇽', continent: 'North America', continentEmoji: '🌎', airport: 'Cancun International Airport', emoji: '🏖️', heroDescription: 'Cancun is the gateway to some of the most extraordinary experiences in the Americas. The ancient Mayan ruins of Chichen Itza and Tulum, the crystal clear cenote swimming holes, the Sian Ka\'an biosphere reserve and the beautiful coral reefs of Cozumel are all incredible. Hire a car and the charming colonial town of Valladolid and the hidden beaches of the Riviera Maya are all within easy reach.' },
  { city: 'Mexico City', country: 'Mexico', countryEmoji: '🇲🇽', continent: 'North America', continentEmoji: '🌎', airport: 'Mexico City International Airport', emoji: '🏙️', heroDescription: 'Mexico City is one of the world\'s great experience destinations. The ancient pyramids of Teotihuacan, the extraordinary Frida Kahlo Museum, the floating gardens of Xochimilco, the world class food scene of Polanco and the incredible street art of Roma Norte are all unforgettable. Hire a car and the beautiful colonial city of Puebla, the Popocatepetl volcano and the Tepoztlan pyramid are all within easy reach.' },
  // SOUTH AMERICA - Brazil
  { city: 'Rio de Janeiro', country: 'Brazil', countryEmoji: '🇧🇷', continent: 'South America', continentEmoji: '🌎', airport: 'Rio de Janeiro Galeao International Airport', emoji: '🏖️', heroDescription: 'Rio de Janeiro is one of the world\'s most spectacular and experience-rich cities. Christ the Redeemer, Copacabana and Ipanema beaches, a samba school visit, hang gliding from Pedra Bonita and the extraordinary Carnival are all unforgettable. Hire a car and the stunning Costa Verde, the charming colonial city of Paraty and the beautiful Ilha Grande are all within easy reach.' },
  { city: 'Sao Paulo', country: 'Brazil', countryEmoji: '🇧🇷', continent: 'South America', continentEmoji: '🌎', airport: 'Sao Paulo Guarulhos International Airport', emoji: '🏙️', heroDescription: 'Sao Paulo is one of the world\'s great cities and a place of extraordinary cultural and culinary experiences. The Pinacoteca art museum, the Japanese quarter of Liberdade, the incredible restaurant scene of Vila Madalena and the Ibirapuera park are all wonderful. Hire a car and the beautiful coastal town of Ubatuba, the stunning Iguazu Falls and the charming colonial city of Ouro Preto are all within reach.' },
  // SOUTH AMERICA - Argentina
  { city: 'Buenos Aires', country: 'Argentina', countryEmoji: '🇦🇷', continent: 'South America', continentEmoji: '🌎', airport: 'Buenos Aires Ezeiza International Airport', emoji: '💃', heroDescription: 'Buenos Aires is one of the world\'s most passionate and culturally rich cities. A tango show in San Telmo, the colourful Caminito of La Boca, the extraordinary steak restaurants of Palermo and the beautiful Recoleta cemetery are all unforgettable experiences. Hire a car and the Tigre delta, the beautiful Uruguayan capital Montevideo and the stunning Pampas are all within easy reach.' },
  // SOUTH AMERICA - Peru
  { city: 'Lima', country: 'Peru', countryEmoji: '🇵🇪', continent: 'South America', continentEmoji: '🌎', airport: 'Jorge Chavez International Airport', emoji: '🦙', heroDescription: 'Lima is one of South America\'s great surprise destinations with an extraordinary food scene that is genuinely world class. The Larco Museum, the Miraflores clifftop park, the Barranco arts district and the incredible ceviche culture are all wonderful experiences. Hire a car and the mysterious Nazca Lines, the stunning Paracas National Reserve and the beautiful Ica desert oasis are all within reach.' },
  // SOUTH AMERICA - Colombia
  { city: 'Medellin', country: 'Colombia', countryEmoji: '🇨🇴', continent: 'South America', continentEmoji: '🌎', airport: 'Jose Maria Cordova International Airport', emoji: '🌸', heroDescription: 'Medellin is one of South America\'s most remarkable transformation stories and an extraordinary city to experience. The cable car communities, the Botero sculptures, the flower festival, the innovative urban spaces and the incredible nightlife of El Poblado are all wonderful. Hire a car and the stunning Guatape reservoir, the beautiful colonial town of Santa Fe de Antioquia and the coffee region are all within reach.' },
  { city: 'Cartagena', country: 'Colombia', countryEmoji: '🇨🇴', continent: 'South America', continentEmoji: '🌎', airport: 'Rafael Nunez International Airport', emoji: '🌺', heroDescription: 'Cartagena is one of the most beautiful and romantic cities in the Americas. The UNESCO listed old town, the colourful streets of Getsemani, the sunset boat trips to the Rosario Islands, the street food and the vibrant salsa scene are all extraordinary experiences. Hire a car and the beautiful Santa Marta, the Tayrona National Park and the stunning Colombian coast are all within reach.' },
  // AFRICA - South Africa
  { city: 'Cape Town', country: 'South Africa', countryEmoji: '🇿🇦', continent: 'Africa', continentEmoji: '🌍', airport: 'Cape Town International Airport', emoji: '🏔️', heroDescription: 'Cape Town is one of the world\'s most beautiful cities and the experiences it offers are simply extraordinary. Table Mountain, the Cape Peninsula, Boulders Beach penguins, the Winelands of Stellenbosch and the incredible restaurant scene are all unforgettable. Hire a car and the dramatic Garden Route, the whale watching at Hermanus and the beautiful Cederberg wilderness are all within easy reach.' },
  { city: 'Johannesburg', country: 'South Africa', countryEmoji: '🇿🇦', continent: 'Africa', continentEmoji: '🌍', airport: 'OR Tambo International Airport', emoji: '🦁', heroDescription: 'Johannesburg is the gateway to extraordinary African experiences. The Apartheid Museum, the Soweto township tour, the vibrant Maboneng arts district and the beautiful Cradle of Humankind are all powerful and moving experiences. Hire a car and the magnificent Kruger National Park for incredible safari experiences, the Drakensberg mountains and the beautiful Panorama Route are all within reach.' },
  // AFRICA - Morocco
  { city: 'Marrakech', country: 'Morocco', countryEmoji: '🇲🇦', continent: 'Africa', continentEmoji: '🌍', airport: 'Marrakech Menara Airport', emoji: '🕌', heroDescription: 'Marrakech is one of the world\'s most sensory and unforgettable destinations. Getting lost in the souks, watching the Djemaa el Fna square come alive at sunset, staying in a riad and experiencing a traditional hammam are all extraordinary. Hire a car and the stunning Atlas Mountain villages, the dramatic Ait Benhaddou kasbah, the rose valley of Dades and the vast Sahara Desert are all within reach for incredible experiences.' },
  { city: 'Casablanca', country: 'Morocco', countryEmoji: '🇲🇦', continent: 'Africa', continentEmoji: '🌍', airport: 'Mohammed V International Airport', emoji: '🌊', heroDescription: 'Casablanca is Morocco\'s most modern and cosmopolitan city with extraordinary experiences including the magnificent Hassan II Mosque, one of the world\'s largest. The Art Deco architecture of the old Medina, the vibrant Corniche and the incredible seafood restaurants are all wonderful. Hire a car and the ancient imperial city of Fes, the blue city of Chefchaouen and the beautiful coastal town of Essaouira are all within reach.' },
  // AFRICA - Tanzania
  { city: 'Zanzibar', country: 'Tanzania', countryEmoji: '🇹🇿', continent: 'Africa', continentEmoji: '🌍', airport: 'Zanzibar Airport', emoji: '🏝️', heroDescription: 'Zanzibar is one of the most exotic and experience-rich destinations in the world. The UNESCO listed Stone Town with its Arabian Nights atmosphere, the spice farm tours, the pristine white beaches of Nungwi, the sea turtle sanctuary of Mnarani and the incredible snorkelling are all extraordinary. Hire a car and discover every corner of this magical island.' },
  // OCEANIA - Australia
  { city: 'Sydney', country: 'Australia', countryEmoji: '🇦🇺', continent: 'Oceania', continentEmoji: '🌏', airport: 'Sydney Kingsford Smith Airport', emoji: '🦘', heroDescription: 'Sydney is one of the world\'s most beautiful and experience-rich cities. The Opera House, Bondi Beach, the Harbour Bridge climb, the Taronga Zoo and the incredible food scene of the Inner West are all extraordinary. Hire a car and the Blue Mountains, the Hunter Valley wine region, the stunning Royal National Park coastal walk and the beautiful Central Coast are all wonderful experiences within easy reach.' },
  { city: 'Melbourne', country: 'Australia', countryEmoji: '🇦🇺', continent: 'Oceania', continentEmoji: '🌏', airport: 'Melbourne Airport', emoji: '☕', heroDescription: 'Melbourne is Australia\'s cultural capital and a city of extraordinary experiences. The laneways coffee and street art culture, the MCG sporting events, the Queen Victoria Market, the incredible restaurant scene of Fitzroy and the Yarra Valley wine region are all wonderful. Hire a car and the Great Ocean Road with its Twelve Apostles is one of the world\'s great road trip experiences.' },
  { city: 'Brisbane', country: 'Australia', countryEmoji: '🇦🇺', continent: 'Oceania', continentEmoji: '🌏', airport: 'Brisbane Airport', emoji: '🌞', heroDescription: 'Brisbane is Australia\'s fastest growing city and a brilliant base for extraordinary Queensland experiences. South Bank, the GOMA art museum and the incredible Story Bridge climb are all wonderful. Hire a car and the stunning Glass House Mountains, the beautiful Sunshine Coast hinterland, the Gold Coast theme parks and the incredible Noosa National Park are all within easy reach.' },
  { city: 'Perth', country: 'Australia', countryEmoji: '🇦🇺', continent: 'Oceania', continentEmoji: '🌏', airport: 'Perth Airport', emoji: '🌊', heroDescription: 'Perth is one of the world\'s most isolated yet beautiful cities and the experiences it offers are unique. The stunning Kings Park, the vibrant Fremantle market and port, the beautiful Cottesloe Beach and the extraordinary quokka selfies on Rottnest Island are all wonderful. Hire a car and the incredible Margaret River wine and surf region, the Pinnacles Desert and the stunning Coral Bay are all within reach.' },
  { city: 'Cairns', country: 'Australia', countryEmoji: '🇦🇺', continent: 'Oceania', continentEmoji: '🌏', airport: 'Cairns Airport', emoji: '🐠', heroDescription: 'Cairns is the gateway to two of the world\'s greatest natural wonders. Snorkelling on the Great Barrier Reef and exploring the ancient Daintree Rainforest are both extraordinary experiences that are simply unlike anything else on earth. Hire a car and the beautiful Atherton Tablelands waterfalls, the dramatic Cape Tribulation and the stunning Mossman Gorge are all within easy reach.' },
  // OCEANIA - New Zealand
  { city: 'Auckland', country: 'New Zealand', countryEmoji: '🇳🇿', continent: 'Oceania', continentEmoji: '🌏', airport: 'Auckland Airport', emoji: '🌋', heroDescription: 'Auckland is New Zealand\'s largest city and a brilliant base for extraordinary experiences. The Sky Tower, the Waiheke Island wine and beach scene, a Maori cultural experience and the beautiful Hauraki Gulf islands are all wonderful. Hire a car and the stunning Coromandel Peninsula, the geothermal wonders of Rotorua, the beautiful Bay of Islands and the dramatic Tongariro National Park are all within reach.' },
  { city: 'Queenstown', country: 'New Zealand', countryEmoji: '🇳🇿', continent: 'Oceania', continentEmoji: '🌏', airport: 'Queenstown Airport', emoji: '🏔️', heroDescription: 'Queenstown is the adventure capital of the world and the experiences here are simply extraordinary. Bungy jumping, skydiving, jet boating, skiing in winter and the stunning Milford Sound cruise are all bucket list experiences. Hire a car and the incredible Fiordland National Park, the beautiful Otago Peninsula wildlife, the stunning Crown Range and the charming town of Wanaka are all within easy reach.' },
  { city: 'Christchurch', country: 'New Zealand', countryEmoji: '🇳🇿', continent: 'Oceania', continentEmoji: '🌏', airport: 'Christchurch Airport', emoji: '🌿', heroDescription: 'Christchurch is New Zealand\'s most fascinating city. Rebuilt after the devastating 2011 earthquake, it is now a showcase of innovative architecture and urban creativity. The Cardboard Cathedral, the incredible street art, the beautiful Botanic Gardens and the Antarctic attraction are all wonderful. Hire a car and the stunning Arthur\'s Pass, the beautiful Akaroa Peninsula and the dramatic Banks Peninsula are all within easy reach.' },
]

async function seedLocations() {
  console.log('Starting to seed locations...')

  for (const location of locations) {
    const citySlug = location.city.toLowerCase().replace(/ /g, '-')
    const countrySlug = location.country.toLowerCase().replace(/ /g, '-')
    const continentSlug = location.continent.toLowerCase().replace(/ /g, '-')

    const existing = await client.fetch(
      `*[_type == "location" && slug.current == $citySlug][0]`,
      { citySlug }
    )

    if (existing) {
      console.log(`Skipping ${location.city} - already exists`)
      continue
    }

    const doc = {
      _type: 'location',
      city: location.city,
      country: location.country,
      countryEmoji: location.countryEmoji,
      continent: location.continent,
      continentEmoji: location.continentEmoji,
      airport: location.airport,
      emoji: location.emoji,
      heroDescription: location.heroDescription,
      slug: { _type: 'slug', current: citySlug },
      countrySlug: { _type: 'slug', current: countrySlug },
      continentSlug: { _type: 'slug', current: continentSlug },
    }

    try {
      await client.create(doc)
      console.log(`Created: ${location.city}, ${location.country}, ${location.continent}`)
    } catch (error) {
      console.error(`Failed to create ${location.city}:`, error)
    }
  }

  console.log('Done!')
}

seedLocations()